#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    dialect: org.hibernate.dialect.PostgreSQL10Dialect
